name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
      -
        name: Push to GitHub Container Registry
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest ghcr.io/${{ secrets.GITHUB_REPOSITORY_OWNER }}/clockbox:latest
          docker push ghcr.io/${{ secrets.GITHUB_REPOSITORY_OWNER }}/clockbox:latest
        env:
          DOCKER_CLI_ACI_USERNAME: ${{ github.actor }}
          DOCKER_CLI_ACI_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
